#
# Makefile for the nubia drivers.
#

obj-$(CONFIG_NUBIA_FINGERPRINT)                   += fingerprint/
obj-$(CONFIG_NUBIA_SENSORS)                       += stk3337/
obj-$(CONFIG_NUBIA_SENSORS_SENS)              	  += sensors_sensitivity/
obj-$(CONFIG_NUBIA_FORK_MONITOR_CTL)                    += fork_monitor_ctl/
obj-$(CONFIG_NUBIA_SCHED_CTL)                    += sched_ctl/
obj-m                                            += freezer/
obj-m                                            += nblog/
