#
# Makefile for the led driver.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_NUBIA_LED)		+= aw22xxx/
obj-$(CONFIG_NUBIA_LED)		+= aw86927/
obj-$(CONFIG_NUBIA_LED)		+= aw86927_double/
obj-m += aw96205/
#obj-$(CONFIG_NUBIA_LED)		+= aw8697/

